### ISSUE TITLE
New version repo issue

### ISSUE THREAD

**Issue by JonnesLin** [ncTimTang/AKS#9]
Hi @ncTimTang ,

We are still having the problem to run the codebase:

All the data files must have the same columns, but at some point there are 3 new columns ({'frame_idx', 'use_topk', 'frame_num'})

This happened while the json dataset builder was generating data using

/root/tmp/AKS/datasets/videomme/include_frame_idx.json

Please either edit the data files to have matching columns, or separate them into different configurations (see docs at https://hf.co/docs/hub/datasets-manual-configuration#multiple-configurations)

Not sure how can you run the code with this issue. Could you check if the current repo is the correct version?

**Comment by ncTimTang** [comment]
Hi @JonnesLin,

I checked the codes again. The code should work correctly now. 

```Shell
All the data files must have the same columns, but at some point there are 3 new columns ({'frame_idx', 'use_topk', 'frame_num'})
```

This issue appeared in the previous version because ‘base_score_path’ in [videomme_aks_llava_video_7b.sh](https://github.com/ncTimTang/AKS/blob/main/evaluation/scripts/llava_video_7b/videomme_aks_llava_video_7b.sh) was wrong, but it has been corrected in the current version. Moreover, please do not remove the execution of change_score.py of [videomme_aks_llava_video_7b.sh](https://github.com/ncTimTang/AKS/blob/main/evaluation/scripts/llava_video_7b/videomme_aks_llava_video_7b.sh), as it will modify the include_frame_idx.json file.

I recommend that you check [videomme_aks_llava_video_7b.sh](https://github.com/ncTimTang/AKS/blob/main/evaluation/scripts/llava_video_7b/videomme_aks_llava_video_7b.sh) first, make sure it's the same as on GitHub. 

If that doesn't work, I've emailed you the ‘include_frame_idx.json’ that have been processed correctly by change_score.py. You can compare the differences with yours, replace the original one with it, and then remove the execution of change_score.py of [videomme_aks_llava_video_7b.sh](https://github.com/ncTimTang/AKS/blob/main/evaluation/scripts/llava_video_7b/videomme_aks_llava_video_7b.sh), and re-execute it.

Hope this can help you. If you have any further questions, please feel free to contact me.

Best,

Tim

**Comment by JonnesLin** [comment]
Thanks Tim @ncTimTang . Very appreciate your help! 

Well, even though i replace my include_frame_idx.json with yours and run it again as your instructions, i still have the same issue.. 

I have sent you some update via email. Thanks!

Best,
JL
